repos:
- repo: https://github.com/rtts/djhtml
  rev: v1.4.10
  hooks:
    - id: djhtml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4
  hooks:
    - id: ruff
      name: ruff check
    - id: ruff-format
      name: ruff format